# Generated by Django 5.1.6 on 2025-07-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_condition', models.CharField(choices=[('responsable_inscripto', 'Responsable inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor final')], default='consumidor_final', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, choices=[('80', 'CUIT'), ('86', 'CUIL'), ('96', 'DNI'), ('89', 'LE'), ('90', 'LC'), ('94', 'PASSPORT')], default='80', max_length=50, null=True)),
                ('number', models.CharField(blank=True, editable=False, max_length=11, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='id_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='clients.iddocument'),
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.account')),
            ],
        ),
    ]
