# Generated by Django 5.1.6 on 2025-04-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('ids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='ids.iddocument'),
        ),
        migrations.AddField(
            model_name='client',
            name='iva_condition',
            field=models.CharField(choices=[('responsable_inscripto', 'Responsable inscripto'), ('monotributista', 'Monotributista'), ('exento', 'Exento'), ('consumidor_final', 'Consumidor final')], default='consumidor_final', max_length=50),
        ),
    ]
