# Generated by Django 5.1.6 on 2025-03-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('factura', 'Factura'), ('remito', 'Remito'), ('presupuesto', 'Presupuesto'), ('recibo', 'Recibo'), ('nota_credito', 'Nota de crédito')], max_length=20)),
                ('document_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('valid_until', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('factura', 'Factura'), ('remito', 'Remito'), ('presupuesto', 'Presupuesto'), ('recibo', 'Recibo'), ('nota_credito', 'Nota de crédito')], max_length=20)),
                ('document_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('factura', 'Factura'), ('remito', 'Remito'), ('presupuesto', 'Presupuesto'), ('recibo', 'Recibo'), ('nota_credito', 'Nota de crédito')], max_length=20)),
                ('document_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('products_delivered', models.TextField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('recipient', models.CharField(max_length=255)),
                ('shipping_address', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('factura', 'Factura'), ('remito', 'Remito'), ('presupuesto', 'Presupuesto'), ('recibo', 'Recibo'), ('nota_credito', 'Nota de crédito')], max_length=20)),
                ('document_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('fiscal_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('factura', 'Factura'), ('remito', 'Remito'), ('presupuesto', 'Presupuesto'), ('recibo', 'Recibo'), ('nota_credito', 'Nota de crédito')], max_length=20)),
                ('document_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.budget')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
