# Generated by Django 5.1.6 on 2025-03-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnote',
            old_name='invoice_related',
            new_name='invoice',
        ),
    ]
