# Generated by Django 5.1.6 on 2025-04-17 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_rename_invoice_related_creditnote_invoice"),
        ("orders", "0004_order_subtotal"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("factura", "Factura"),
                            ("remito", "Remito"),
                            ("presupuesto", "Presupuesto"),
                            ("recibo", "Recibo"),
                            ("nota_credito", "Nota de crédito"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_letter",
                    models.CharField(
                        choices=[
                            ("001", "A"),
                            ("006", "B"),
                            ("011", "C"),
                            ("099", "X"),
                        ],
                        default="099",
                        max_length=3,
                    ),
                ),
                ("document_number", models.CharField(editable=False, max_length=8)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="documents/pdf/"),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("generated", models.BooleanField(default=False)),
                ("products_returned", models.TextField()),
                ("observations", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="fiscal_data",
            new_name="b64_fiscal_data",
        ),
        migrations.AddField(
            model_name="budget",
            name="document_letter",
            field=models.CharField(
                choices=[("001", "A"), ("006", "B"), ("011", "C"), ("099", "X")],
                default="099",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="budget",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/pdf/"),
        ),
        migrations.AddField(
            model_name="budget",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="document_letter",
            field=models.CharField(
                choices=[("001", "A"), ("006", "B"), ("011", "C"), ("099", "X")],
                default="099",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/pdf/"),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="document_letter",
            field=models.CharField(
                choices=[("001", "A"), ("006", "B"), ("011", "C"), ("099", "X")],
                default="099",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/pdf/"),
        ),
        migrations.AddField(
            model_name="deliverynote",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="document_letter",
            field=models.CharField(
                choices=[("001", "A"), ("006", "B"), ("011", "C"), ("099", "X")],
                default="099",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="invoice",
            name="json_arca_request",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/pdf/"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="document_letter",
            field=models.CharField(
                choices=[("001", "A"), ("006", "B"), ("011", "C"), ("099", "X")],
                default="099",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="receipt",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="documents/pdf/"),
        ),
        migrations.AddField(
            model_name="receipt",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="document_number",
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="document_number",
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name="deliverynote",
            name="document_number",
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="document_number",
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name="receipt",
            name="document_number",
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AddConstraint(
            model_name="creditnote",
            constraint=models.UniqueConstraint(
                fields=("document_type", "document_letter", "document_number", "store"),
                name="unique_credit_note_document_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("document_type", "document_letter", "document_number", "store"),
                name="unique_invoice_document_per_store",
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="return",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stores.store",
            ),
        ),
    ]
