# Generated by Django 5.1.6 on 2025-04-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_invoice_unique_invoice_document_per_store_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditnote',
            name='unique_credit_note_document_per_store',
        ),
        migrations.AddConstraint(
            model_name='creditnote',
            constraint=models.UniqueConstraint(fields=('document_type', 'document_letter', 'document_number', 'store'), name='unique_credit_note_document_per_store'),
        ),
    ]
