# Generated by Django 5.1.6 on 2025-04-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva_condition', models.CharField(choices=[('responsable_inscripto', 'Responsable inscripto'), ('monotributista', 'Monotributista')], default='responsable_inscripto', max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=20)),
                ('cbu', models.CharField(max_length=22)),
            ],
        ),
    ]
