# Generated by Django 5.1.6 on 2025-07-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='iva_condition',
            new_name='vat_condition',
        ),
        migrations.AddField(
            model_name='store',
            name='gross_income_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_number',
            field=models.CharField(editable=False, max_length=4, null=True, unique=True),
        ),
    ]
