# Generated by Django 5.1.6 on 2025-04-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tav',
            field=models.PositiveSmallIntegerField(choices=[(1, 'No Gravado'), (2, 'Exento'), (3, '0%'), (4, '10,50%'), (5, '21%'), (6, '27%'), (7, 'Gravado'), (8, '5%'), (9, '2,50%')], default=5),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
